### ISSUE TITLE
suggestion : use peertube-import-videos.js

### ISSUE THREAD

**Issue by gnouts** [mister-monster/YouTube2PeerTube#7]
Why don't you use the already existing script from peertube ?
This is a suggestion (or maybe I'm missing some of your goals)

peertube-import-videos.js tells the server to download the video from youtube directly. If you run the script from your pc (and not the peertube server) it could save you bandwitdth and disk space.
Also it downloads thumbnail and description and tags in one command.

The only downside : peertube is required locally to build the peertube-import-videos.js. Though since v1.4.0 we can build only cli tools and not the whole peertube server : https://docs.joinpeertube.org/#/maintain-tools?id=installation

FTR I have a project that do the same, it's a bit dirty as I'm not really a dev. So I'm looking for a nicer and better maintained project like yours. I might give it a try :)
Feel free to copy it, though it suffer from the same limitation (no database, password in cleartext, etc) https://taboulisme.com/git/nouts/peertube-import

**Comment by mister-monster** [comment]
The answer to that question is in the README.md file. This tool is for watching YT channels and getting videos as they appear in the channel, the tool you're referencing cannot do that.
